## ActivitySim
## See full license in LICENSE.txt.


#HHT_NONE: 0
#HHT_FAMILY_MARRIED: 1
#HHT_FAMILY_MALE: 2
#HHT_FAMILY_FEMALE: 3
#HHT_NONFAMILY_MALE_ALONE: 4
#HHT_NONFAMILY_MALE_NOTALONE: 5
#HHT_NONFAMILY_FEMALE_ALONE: 6
#HHT_NONFAMILY_FEMALE_NOTALONE: 7

# convenience for expression files
HHT_NONFAMILY: [4, 5, 6, 7]
HHT_FAMILY: [1, 2, 3]

PSTUDENT_GRADE_OR_HIGH: 1
PSTUDENT_UNIVERSITY: 2
PSTUDENT_NOT: 3

GRADE_SCHOOL_MAX_AGE: 14
GRADE_SCHOOL_MIN_AGE: 5

SCHOOL_SEGMENT_NONE: 0
SCHOOL_SEGMENT_GRADE: 1
SCHOOL_SEGMENT_HIGH: 2
SCHOOL_SEGMENT_UNIV: 3

INCOME_SEGMENT_LOW: 1
INCOME_SEGMENT_MED: 2
INCOME_SEGMENT_HIGH: 4
INCOME_SEGMENT_VERYHIGH: 5

PEMPLOY_FULL: 1
PEMPLOY_PART: 2
PEMPLOY_NOT: 3
PEMPLOY_CHILD: 4

PTYPE_FULL: &ptype_full 1
PTYPE_PART: &ptype_part 2
PTYPE_UNIVERSITY: &ptype_university 3
PTYPE_NONWORK: &ptype_nonwork 4
PTYPE_RETIRED: &ptype_retired 5
PTYPE_DRIVING: &ptype_driving 6
PTYPE_SCHOOL: &ptype_school 7
PTYPE_PRESCHOOL:  &ptype_preschool 8

# these appear as column headers in non_mandatory_tour_frequency.csv
PTYPE_NAME:
  *ptype_full: PTYPE_FULL
  *ptype_part: PTYPE_PART
  *ptype_university: PTYPE_UNIVERSITY
  *ptype_nonwork: PTYPE_NONWORK
  *ptype_retired: PTYPE_RETIRED
  *ptype_driving: PTYPE_DRIVING
  *ptype_school: PTYPE_SCHOOL
  *ptype_preschool: PTYPE_PRESCHOOL


CDAP_ACTIVITY_MANDATORY: M
CDAP_ACTIVITY_NONMANDATORY: N
CDAP_ACTIVITY_HOME: H

distributed_time_factor_work_mean: 1.0
distributed_time_factor_work_stddev: 0.7
distributed_time_factor_nonwork_mean: 1.0
distributed_time_factor_nonwork_stddev: 0.6
distributed_time_factor_min: 0.1
distributed_time_factor_max: 10

# year after which a vehicle (therefore its household) must have transponder
hhTR_Vehyear: 2035

minimumAgeDA: 16

# Mode Choice Constants
#valueOfTime: 8.00
costPerMile: 18.29
cost_share_s2: 1.75
cost_share_s3: 2.50
waitThresh: 10.00
walkThresh: 1.50
shortWalk: 0.333
longWalk: 0.667
walkSpeed: 2.5 #reduced from 3, from survey: mean=2.163, median=2.475, 3q=2.846
bikeThresh: 6.00
bikeSpeed: 10.00 #reduced from 12, from survey: mean=7.687, median=7.69, 3q=10.262
vot_threshold_low: 8.81
vot_threshold_med: 18.00
maxCbdAreaTypeThresh: 2
AV_IVT_factor: 1.0 #FIXME: I think this is related to AV, needs to be fully implemented
indivTour: 1.00000
# RIDEHAIL Settings
Taxi_baseFare: 2.20
Taxi_costPerMile: 2.30
Taxi_costPerMinute: 0.10
Taxi_waitTime_mean:
  1: 5.5
  2: 9.5
  3: 13.3
  4: 17.3
  5: 26.5
Taxi_waitTime_sd:
  1: 0
  2: 0
  3: 0
  4: 0
  5: 0
TNC_single_baseFare: 2.20
TNC_single_costPerMile: 1.33
TNC_single_costPerMinute: 0.24
TNC_single_costMinimum: 7.20
TNC_single_waitTime_mean:
  1: 3.0
  2: 6.3
  3: 8.4
  4: 8.5
  5: 10.3
TNC_single_waitTime_sd:
  1: 0
  2: 0
  3: 0
  4: 0
  5: 0
TNC_shared_baseFare: 2.20
TNC_shared_costPerMile: 0.53
TNC_shared_costPerMinute: 0.10
TNC_shared_costMinimum: 3.00
TNC_shared_IVTFactor: 1.5
TNC_shared_waitTime_mean:
  1: 5.0
  2: 8.0
  3: 11.0
  4: 15.0
  5: 15.0
TNC_shared_waitTime_sd:
  1: 0
  2: 0
  3: 0
  4: 0
  5: 0
min_waitTime: 0
max_waitTime: 50

ivt_cost_multiplier: 0.6
ivt_pmov_multiplier: 1.0
ivt_stcar_multiplier: 0.9
ivt_brt_multiplier: 0.9
ivt_urb_multiplier: 0.8
ivt_com_multiplier: 0.7
walktimeshort_multiplier: 2
walktimelong_multiplier: 10
biketimeshort_multiplier: 4
biketimelong_multiplier: 20
short_i_wait_multiplier: 2
long_i_wait_multiplier: 1
wacc_multiplier: 2
wegr_multiplier: 2
waux_multiplier: 2
dtim_multiplier: 2
xwait_multiplier: 2
dacc_ratio: 0
xfers_wlk_multiplier: 10
xfers_drv_multiplier: 20
drvtrn_distpen_0_multiplier: 270
drvtrn_distpen_max: 15
density_index_multiplier: -0.2
#    joint_sr2_ASC_no_auto: 0
#    joint_sr2_ASC_auto_deficient: 0
#    joint_sr2_ASC_auto_sufficient: 0
#    joint_drive_transit_ASC_no_auto: 0

I_MODE_MAP:
  DRIVEALONE: 1
  SHARED2: 2
  SHARED3: 3
  WALK: 4
  BIKE: 5
  TRNWALKACCESS: 6
  TRNDRIVEACCESS: 7
  SCHOOLBUS: 8
  TAXI: 9
  TNC_SINGLE: 10
  TNC_SHARED: 11
I_SOV_MODES: [1]
I_SR2_MODES: [2]
I_SR3P_MODES: [3]
I_AUTO_MODES: [1, 2, 3]
I_WALK_MODE: 4
I_BIKE_MODE: 5
I_WALK_TRANSIT_MODES: [6]
I_DRIVE_TRANSIT_MODES: [7]
I_SCHOOLBUS_MODE: [8]
I_RIDE_HAIL_MODES: [9, 10, 11]
I_TAXI_MODE: 9
I_TNC_SINGLE_MODE: 10
I_TNC_SHARED_MODE: 11
