
inherit_settings: True

shadow_pricing_models:
  workplace: workplace_location
  school: school_location
  

# global switch to enable/disable loading of saved shadow prices
# (ignored if global use_shadow_pricing switch is False)
LOAD_SAVED_SHADOW_PRICES: True

# number of shadow price iterations for cold start
MAX_ITERATIONS: 10

# number of shadow price iterations for warm start (after loading saved shadow_prices)
MAX_ITERATIONS_SAVED: 1

# ignore criteria for zones smaller than size_threshold
SIZE_THRESHOLD: 10

# zone passes if modeled is within percent_tolerance of  predicted_size
PERCENT_TOLERANCE: 5

# max percentage of zones allowed to fail
FAIL_THRESHOLD: 1

# ctramp-style shadow_pricing_method parameters
DAMPING_FACTOR: 1

# daysim-style shadow_pricing_method parameters
# FIXME should these be the same as PERCENT_TOLERANCE and FAIL_THRESHOLD above?
DAYSIM_ABSOLUTE_TOLERANCE: 50
DAYSIM_PERCENT_TOLERANCE: 10

SHADOW_PRICE_METHOD: simulation

# --- simulation method settings
# apply different targets for each segment specified in destination_size_terms.csv
school_segmentation_targets:
  # format is segment: land_use_column
  university: ENROLLED
  mn_gradesch: mn_gradesch
  mn_hisch: mn_hisch
  wi_gradesch: wi_gradesch
  wi_hisch: wi_hisch

# if target names are the same, they will be combined together
workplace_segmentation_targets:
  # using total employment scaled to remove external workers. see annotate_landuse.csv
  work_low: ADJ_TOT_EMP
  work_med: ADJ_TOT_EMP
  work_high: ADJ_TOT_EMP
  work_veryhigh: ADJ_TOT_EMP

# ignore criteria for zones smaller than target_threshold (total employmnet or enrollment)
TARGET_THRESHOLD: 10
