SPEC: transit_pass_subsidy.csv
COEFFICIENTS: transit_pass_subsidy_coeffs.csv

#LOGIT_TYPE: NL
LOGIT_TYPE: MNL

preprocessor:
  SPEC: transit_pass_subsidy_annotate_choosers
  DF: persons
  TABLES:
    - accessibility

CHOOSER_FILTER_COLUMN_NAME: transit_subsidy_available
