LOGIT_TYPE: NL

NESTS:
  name: root
  coefficient: coef_nest_root
  alternatives:
      - name: AUTO
        coefficient: coef_nest_AUTO
        alternatives:
            - DRIVEALONE
            - SHARED2
            - SHARED3
      - name: NONMOTORIZED
        coefficient: coef_nest_NONMOTORIZED
        alternatives:
          - WALK
          - BIKE
      - name: TRANSIT
        coefficient:  coef_nest_TRANSIT
        alternatives:
            - TRNWALKACCESS
            - TRNDRIVEACCESS
      - name: SCHOOL_BUS
        coefficient: coef_nest_SCHOOL_BUS
        alternatives:
          - SCHOOLBUS
      - name: RIDEHAIL
        coefficient: coef_nest_RIDEHAIL
        alternatives:
          - TAXI
          - TNC_SINGLE
          - TNC_SHARED

SPEC: trip_mode_choice.csv
COEFFICIENTS: trip_mode_choice_coefficients.csv
COEFFICIENT_TEMPLATE: trip_mode_choice_coefficients_template.csv

CONSTANTS:
  orig_col_name: origin
  dest_col_name: destination
  

# so far, we can use the same spec as for non-joint tours
preprocessor:
  SPEC: trip_mode_choice_annotate_trips_preprocessor
  DF: df
  TABLES:
    - land_use
    - tours
    - persons

#  - SPEC: trip_mode_choice_annotate_trips_preprocessor2
#    DF: df
#    TABLES:
#      - land_use

# to reduce memory needs filter chooser table to these fields
TOURS_MERGED_CHOOSER_COLUMNS:
  - hhsize
  - age
  - auto_ownership
  - number_of_participants
  - tour_category
  - parent_tour_id
  - tour_mode
  - duration
  - value_of_time
  - tour_type
  - free_parking_at_work


MODE_CHOICE_LOGSUM_COLUMN_NAME: mode_choice_logsum
