# read cached skims (using numpy memmap) from output directory (memmap is faster than omx )
read_skim_cache: True
# write memmapped cached skims to output directory after reading from omx, for use in subsequent runs
write_skim_cache: True

#alternate dir to read/write skim cache (defaults to output_dir)
#cache_dir: data/cache

zone_system: 1

taz_skims: allskims.omx

skim_time_periods:
    time_window: 1440
    period_minutes: 30
    periods: [0, 8, 18, 26, 48]
    labels: ['AM', 'MD', 'PM', 'NT']