# read cached skims (using numpy memmap) from output directory (memmap is faster than omx )
read_skim_cache: True
# write memmapped cached skims to output directory after reading from omx, for use in subsequent runs
write_skim_cache: True

#alternate dir to read/write skim cache (defaults to output_dir)
#cache_dir: data/cache

zone_system: 1

taz_skims: allskims.omx

# Index 0 = 3 AM
# EA =  ..NT..      /  0- 5
# AM = 6 AM - 10 AM /  6-13
# MD = 10 AM - 3 PM / 14-23
# PM = 3 PM - 7 PM  / 24-31
# NT = 7 PM - 6 AM  / 32-48
skim_time_periods:
    time_window: 1440
    period_minutes: 30
    periods: [0, 5, 13, 23, 31, 48]
    labels: ['EA', 'AM', 'MD', 'PM', 'NT']