# Configs File with Sample Rate set by Model Runner
inherit_settings: True
# raise error if any sub-process fails without waiting for others to complete
fail_fast: True
# - ------------------------- dev config
multiprocess: True
strict: False
mem_tick: 30
use_shadow_pricing: False
## - example sample
households_sample_size: 100000
chunk_training_mode: disabled
chunk_size: 100_000_000_000
num_processes: 10
default_initial_rows_per_chunk: 1000000000
# - tracing
# trace_hh_id: 214
# trace_hh_id: 1986
# trace_hh_id: 4218
# trace_hh_id: 345105 
# trace_hh_id: 345208
# trace_hh_id: 345490
#trace_hh_id: 346694
trace_hh_id: 729358
#trace_od:

# input tables
input_table_list:
  #
  # persons (table index 'person_id')
  #
  - tablename: persons
    filename: persons.csv
    index_col: person_id
    rename_columns:
      GENDER: sex
      EmpStatus: ESR
      
  #
  # households (table index 'household_id')
  #
  - tablename: households
    filename: households.csv
    index_col: household_id
    rename_columns:
      HHZON: home_zone_id
      HCHILDREN: children
      HHSIZE: hhsize
 
  #
  # land_use (table index 'zone_id')
  #
  - tablename: land_use
    filename: land_use.csv
    index_col: zone_id

# set false to disable variability check in simple_simulate and interaction_simulate
check_for_variability: False

# area_types less than this are considered urban
urban_threshold: 4
cbd_threshold: 2
rural_threshold: 6

# value_of_time = lognormal(np.log(median_value_of_time * mu), sigma).clip(min_vot, max_vot)

min_value_of_time: 1
max_value_of_time: 50
distributed_vot_mu: 0.684
distributed_vot_sigma: 0.85

household_median_value_of_time:
  1: 6.01
  2: 8.81
  3: 10.44
  4: 12.86
  5: 15.08


#trace_od: [5, 11]
# to resume after last successful checkpoint, specify resume_after: _
#resume_after: cdap_simulate
models:
  ### mp_initialize step
  - initialize_landuse
  - compute_accessibility
  - initialize_households
  ### mp_households step
  - school_location
  - workplace_location
  - work_from_home
  - auto_ownership_simulate
  - free_parking
  - telecommute_frequency
  - cdap_simulate
  - mandatory_tour_frequency
  - mandatory_tour_scheduling
  - joint_tour_frequency
  - joint_tour_composition
  - joint_tour_participation
  - joint_tour_destination
  - joint_tour_scheduling
  - non_mandatory_tour_frequency
  - non_mandatory_tour_destination
  - non_mandatory_tour_scheduling
  - tour_mode_choice_simulate
  - atwork_subtour_frequency
  - atwork_subtour_destination
  - atwork_subtour_scheduling
  - atwork_subtour_mode_choice
  - stop_frequency
  - trip_purpose
  - trip_destination
  - trip_purpose_and_destination
  - trip_scheduling
  - trip_mode_choice
  ### mp_summarize step
  - write_data_dictionary
  - write_tables
  - write_trip_matrices

multiprocess_steps:
  - name: mp_initialize
    begin: initialize_landuse
  - name: mp_households
    begin: school_location
    slice:
      tables:
        - households
        - persons
  - name: mp_summarize
    begin: write_data_dictionary
output_tables:
  action: include
  prefix: final_
  tables:
    - checkpoints
    - accessibility
    - land_use
    - households
    - persons
    - tours
    - trips
    - joint_tour_participants
#    - school_shadow_prices
#    - workplace_shadow_prices


