# input tables
#
# activitysim uses "well-known" index and foreign key names for imported tables (e.g. households, persons, land_use)
# as well as for created tables (tours, joint_tour_participants, trips)
# e.g. the households table must have an index column 'household_id' and the foreign key to households in the
# persons table is also household_id. This naming convention allows activitysim to intuit the relationship
# between tables - for instance, to ensure that multiprocess slicing includes all the persons, tours, and trips
# in the same subprocess pipeline. The same strategy is also when chunking choosers, and to support tracing by
# household_id.
#
# the input_table_list index_col directive instructs activitysim to set the imported table index to zone_id
# you cannot change the well-known name of the index by modifying this directive. However, if your input file
# has a different id column name, you can rename it to the required index name with the rename_columns directive.
# In the settings below, the 'TAZ' column in the imported table is renamed 'zone_id' in the rename_columns settings.
#
# input tables
input_table_list:
  #
  # households (table index 'household_id')
  #
  - tablename: households
    filename: households.csv
    index_col: household_id
    rename_columns:
      HHZON: home_zone_id
      HCHILDREN: children
      HHSIZE: hhsize
      
  #
  # persons (table index 'person_id')
  #
  - tablename: persons
    filename: persons.csv
    index_col: person_id
    rename_columns:
      GENDER: sex
      EmpStatus: ESR
      PTYPE: ptype
      
  #
  # land_use (table index 'zone_id')
  #
  - tablename: land_use
    filename: land_use.csv
    index_col: zone_id
    
# set false to disable variability check in simple_simulate and interaction_simulate
check_for_variability: False

# area_types less than this are considered urban
urban_threshold: 4
cbd_threshold: 2
rural_threshold: 6

# value_of_time = lognormal(np.log(median_value_of_time * mu), sigma).clip(min_vot, max_vot)

min_value_of_time: 1
max_value_of_time: 50
distributed_vot_mu: 0.684
distributed_vot_sigma: 0.85

household_median_value_of_time:
  1: 6.01
  2: 8.81
  3: 10.44
  4: 12.86
  5: 15.08
