# read trips table post preprocessor and run expressions to code
# additional data fields, with one data fields for each matrix specified below

preprocessor:
  SPEC: write_trip_matrices_annotate_trips_preprocessor
  DF: trips
  TABLES:
    - tours

# divide trip counts by household expansion factor
HH_EXPANSION_WEIGHT_COL: sample_rate  # added when households read in

# save preprocessed trips table to pipeline if desired
SAVE_TRIPS_TABLE: True

MATRICES:
  - file_name: trips_nt.omx
    tables:
      - name: DRIVEALONE
        data_field: DRIVEALONE_NT
      - name: SHARED2
        data_field: SHARED2_NT
      - name: SHARED3
        data_field: SHARED3_NT
      - name: WALK
        data_field: WALK_NT
      - name: BIKE
        data_field: BIKE_NT
      - name: TRN_WALK
        data_field: TRNWALKACCESS_NT
      - name: TRN_DRV
        data_field: TRNDRIVEACCESS_NT
      - name: SCHOOLBUS
        data_field: SCHOOLBUS_NT
      - name: TAXI
        data_field: TAXI_NT
      - name: TNC_SINGLE
        data_field: TNC_SINGLE_NT
      - name: TNC_SHARED
        data_field: TNC_SHARED_NT
  - file_name: trips_am.omx
    tables:
      - name: DRIVEALONE
        data_field: DRIVEALONE_AM
      - name: SHARED2
        data_field: SHARED2_AM
      - name: SHARED3
        data_field: SHARED3_AM
      - name: WALK
        data_field: WALK_AM
      - name: BIKE
        data_field: BIKE_AM
      - name: TRN_WALK
        data_field: TRNWALKACCESS_AM
      - name: TRN_DRV
        data_field: TRNDRIVEACCESS_AM
      - name: SCHOOLBUS
        data_field: SCHOOLBUS_AM
      - name: TAXI
        data_field: TAXI_AM
      - name: TNC_SINGLE
        data_field: TNC_SINGLE_AM
      - name: TNC_SHARED
        data_field: TNC_SHARED_AM
  - file_name: trips_md.omx
    tables:
      - name: DRIVEALONE
        data_field: DRIVEALONE_MD
      - name: SHARED2
        data_field: SHARED2_MD
      - name: SHARED3
        data_field: SHARED3_MD
      - name: WALK
        data_field: WALK_MD
      - name: BIKE
        data_field: BIKE_MD
      - name: TRN_WALK
        data_field: TRNWALKACCESS_MD
      - name: TRN_DRV
        data_field: TRNDRIVEACCESS_MD
      - name: SCHOOLBUS
        data_field: SCHOOLBUS_MD
      - name: TAXI
        data_field: TAXI_MD
      - name: TNC_SINGLE
        data_field: TNC_SINGLE_MD
      - name: TNC_SHARED
        data_field: TNC_SHARED_MD
  - file_name: trips_pm.omx
    tables:
      - name: DRIVEALONE
        data_field: DRIVEALONE_PM
      - name: SHARED2
        data_field: SHARED2_PM
      - name: SHARED3
        data_field: SHARED3_PM
      - name: WALK
        data_field: WALK_PM
      - name: BIKE
        data_field: BIKE_PM
      - name: TRN_WALK
        data_field: TRNWALKACCESS_PM
      - name: TRN_DRV
        data_field: TRNDRIVEACCESS_PM
      - name: SCHOOLBUS
        data_field: SCHOOLBUS_PM
      - name: TAXI
        data_field: TAXI_PM
      - name: TNC_SINGLE
        data_field: TNC_SINGLE_PM
      - name: TNC_SHARED
        data_field: TNC_SHARED_PM

CONSTANTS:
  time_periods:
    NT1:
      first_hour: 1
      last_hour: 11
    AM:
      first_hour: 12
      last_hour: 19
    MD:
      first_hour: 20
      last_hour: 29
    PM:
      first_hour: 30
      last_hour: 37
    NT2:
      first_hour: 38
      last_hour: 48

  # SHARED2 and SHARED2 Occupancies
  OCC_SHARED2: 2.0
  OCC_SHARED3: 3.33
