; Script for program MATRIX in file "C:\Projects\TourCast\MetCouncilCodeBase\Cube\Catalog\CUBE\TCMAT00B.S"
; Do not change filenames or add or remove FILEI/FILEO statements using an editor. Use Cube/Application Manager.
RUN PGM=MATRIX MSG='Set Inputs and Intermediate File Names - Part 2'
FILEO PRINTO[1] = "%CATALOG_DIR%\TourCast\Script\MatrixKeyValues.py"

;The python configuration file has variable references like this:
;DataReferences=%"Files":___FILE___% where ___FILE___ is a variable holding the file path
;This Matrix module writes these lines out to a Python file that is imported by the config files.  

Zones=1    ;a Cube setting required for record file processing

If (_writefiles==0) 
  Print printo=1 List='#These lines are generated by Cube to pass file names from Catalog Keys to Python Configuration'
  Print printo=1 List='cube___OD_DISTANCE_MATRIX___ = r"', '%SCENARIO_DIR%\AM_HWY_%ITER%.skm', '"'
  Print printo=1 List='cube___AM_PEAK_MATRIX___ = r"', '%SCENARIO_DIR%\AM_HWY_%ITER%.skm', '"'
  Print printo=1 List='cube___MIDDAY_MATRIX___ = r"', '%SCENARIO_DIR%\MD_HWY_%ITER%.skm', '"'
  Print printo=1 List='cube___PM_PEAK_MATRIX___ = r"', '%SCENARIO_DIR%\PM_HWY_%ITER%.skm', '"'
  Print printo=1 List='cube___OVERNIGHT_MATRIX___ = r"', '%SCENARIO_DIR%\NT_HWY_%ITER%.skm', '"'
  Print printo=1 List='cube___NM_MATRIX___ = r"', '%SCENARIO_DIR%\DAILY_NM.skm', '"'  
  Print printo=1 List='cube___PEAK_WALK_TO_TRANSIT_MATRIX___ = r"', '%SCENARIO_DIR%\PK_XIT_WK_%ITER%.skm', '"'
  Print printo=1 List='cube___PEAK_DRIVE_TO_TRANSIT_MATRIX___ = r"', '%SCENARIO_DIR%\PK_XIT_DR_%ITER%.skm', '"'
  Print printo=1 List='cube___OFF_PEAK_WALK_TO_TRANSIT_MATRIX___ = r"', '%SCENARIO_DIR%\OP_XIT_WK_%ITER%.skm', '"'
  Print printo=1 List='cube___OFF_PEAK_DRIVE_TO_TRANSIT_MATRIX___ = r"', '%SCENARIO_DIR%\OP_XIT_DR_%ITER%.skm', '"'
  Print printo=1 List='AMPeak___TRIP_TABLE_MATRIX___ = r"', '%SCENARIO_DIR%\AM_HWY_%ITER%.trp', '"'
  Print printo=1 List='Midday___TRIP_TABLE_MATRIX___ = r"', '%SCENARIO_DIR%\MD_HWY_%ITER%.trp', '"'
  Print printo=1 List='PMPeak___TRIP_TABLE_MATRIX___ = r"', '%SCENARIO_DIR%\PM_HWY_%ITER%.trp', '"'
  Print printo=1 List='Overnight___TRIP_TABLE_MATRIX___ = r"', '%SCENARIO_DIR%\NT_HWY_%ITER%.trp', '"'
  Print printo=1 List='PeakTransit___TRIP_TABLE_MATRIX___ = r"', '%SCENARIO_DIR%\PK_XIT_%ITER%.trp', '"'
  Print printo=1 List='OffPeakTransit___TRIP_TABLE_MATRIX___ = r"', '%SCENARIO_DIR%\OP_XIT_%ITER%.trp', '"'
	Print printo=1 List='#End of Cube generated lines'
  _writefiles=1
Endif 

ENDRUN


