; Do not change filenames or add or remove FILEI/FILEO statements using an editor. Use Cube/Application Manager.

*copy "%SCENARIO_DIR%\transit\XIT_WKACC_NTL_%TPER%.tmp"+"%TRANSIT_FOLDER%\WalkOverrides.txt" "%SCENARIO_DIR%\transit\XIT_WKACC_NTL_%TPER%.ntl"
*copy "%SCENARIO_DIR%\transit\XIT_XFER_NTL_%TPER%.tmp"+"%TRANSIT_FOLDER%\TransferOverrides.txt" "%SCENARIO_DIR%\transit\XIT_XFER_NTL_%TPER%.ntl"
*copy "%SCENARIO_DIR%\transit\XIT_DRACC_NTL_0_%TPER%.tmp"+"%TRANSIT_FOLDER%\DriveOverrides.txt" "%SCENARIO_DIR%\transit\XIT_DRACC_NTL_0_%TPER%.ntl"
